### ISSUE TITLE
refinementList with ::

### ISSUE THREAD

**Issue by victorbosh** [typesense/typesense-instantsearch-adapter#20]
I have some strings in facet values like Lvl::Itermediate

When selected in refinementList XHR request is like filter_by=facet_attribute:%3D[Lvl] (missing ::Itermediate) and no results found

What I need to do?

**Comment by jasonbosco** [comment]
@victorbosh Good catch. I just pushed out a fix to address this issue in this pre-release version: `v0.3.2-0`. Could you try it out and let me know if it works now?

**Comment by victorbosh** [comment]
Hm, still not looks good. On the facet named sp with option like Lvl::basic request is filter_by=:Lvl:sp:%3D[basic]

**Comment by jasonbosco** [comment]
@victorbosh Hopefully it's fixed in `v0.3.2-1`. Could you try now?

I had previously only accounted for colons in facet names. Fixed it now to handle colons in both facet names and values.

**Comment by victorbosh** [comment]
hm, still the same. Maybe I'm doing it wrong.

**Comment by jasonbosco** [comment]
Hmm, could you open your node_modules director, look for typesense-instantsearch-adapter and check if you see a Regex like this: https://github.com/typesense/typesense-instantsearch-adapter/commit/dc86f13532106a51a76661651dd46fbb4bcc9180#diff-65bb0cf938b9195036cb0f06f2a914167c19595eece2ceee699391301b05ac1eR38 in the `SearchRequestAdapter.js` file?

**Comment by victorbosh** [comment]
It works now, for some reason webpack didn't compile it at first. Thanks.
Off topic - do you plan to allow adding some kind of metatags in schema facet: true arrays?
Like multidimensional arrays with {facet_value_to_filter, id, etc...).
Sometimes it will be very nice, like if one want to send some analytics on click but not by name but by id of it

**Comment by jasonbosco** [comment]
Great. I'll push this out in a new release shortly. 

re: your question, you could define one field with facet:true with just the facet values. And then in a separate unindexed field, you could store your multidimensional array with any additional metadata you need. On click, you'll have access to the whole document, so you can access this other unindexed field to fetch the IDs. Does that help?

**Comment by victorbosh** [comment]
Not really, I was talking about on click on facet option, not on document one. Lets say a color facet with 'green' and 'blue' options. On click one of those it will be very helpful to have not the name but id. Or any other data about this facet option

**Comment by jasonbosco** [comment]
Ah I see. This is not ideal - but you could encode the ID into the facet value, so something like `id-facetvalue` when you index it. Then when rendering the facet values using say a refinementList you can use the [`transformItems`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-transformitems) method to parse the ID and display value into separate fields. You can then render the ID into say a data attribute to use in a click handler.

**Comment by victorbosh** [comment]
Yes, that is what I'm doing. But for that to happened I need to provide an js array additionally and pam ids to names or whatever

**Comment by jasonbosco** [comment]
Yeah, not ideal. Mind opening this as a separate issue in the typesense core repo: https://github.com/typesense/typesense?

**Comment by jasonbosco** [comment]
Separately, I've pushed out `v0.3.2` with the colon fix.
